export const MAKE_GRID = 'MAKE_GRID';

export const SET_GRID = 'SET_GRID';
export const SET_START = 'SET_START';
export const SET_END = 'SET_END';

export const TOGGLE_ALGORITHM = 'TOGGLE_ALGORITHM';
export const ADD_RESULT = 'ADD_RESULT';
export const NEXT_LEVEL_HANDLER = 'NEXT_LEVEL_HANDLER';
export const MAX_LEVEL_HANDLER = 'MAX_LEVEL_HANDLER';
export const ADD_BLOCKS = 'ADD_BLOCKS';

export const HANDLE_ALGORITHM_REPLAY = 'HANDLE_ALGORITHM_REPLAY';
export const HANDLE_NO_RESULT = 'HANDLE_NO_RESULT';
export const HANDLE_GAME_START = 'HANDLE_GAME_START';
export const GAME_RESET_HANDLER = 'GAME_RESET_HANDLER';
export const GAME_CONFIG_RESET_HANDLER = 'GAME_CONFIG_RESET_HANDLER';
export const AUTOMATIC_HANDLER = 'AUTOMATIC_HANDLER';
