export const MAKE_GRID = 'MAKE_GRID';

export const CHANGE_COLUMN_SIZE = 'CHANGE_COLUMN_SIZE';
export const CHANGE_ROW_SIZE = 'CHANGE_ROW_SIZE';

export const CHANGE_START_X = 'CHANGE_START_X';
export const CHANGE_START_Y = 'CHANGE_START_Y';

export const CHANGE_END_X = 'CHANGE_END_X';
export const CHANGE_END_Y = 'CHANGE_END_Y';

export const TOGGLE_ALGORITHM = 'TOGGLE_ALGORITHM';
export const ADD_RESULT = 'ADD_RESULT';
export const NEXT_LEVEL_HANDLER = 'NEXT_LEVEL_HANDLER';
